name: Test

on:
  push:
    branches:
      main
  pull_request:
    branches:
      main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: rffontenelle/sphinx-lint-problem-matcher@${{ github.sha }}
    - run: pip install sphinx-lint
    - run: sphinx-lint ./github/file.rst