name: Test

on:
  push:
    branches:
      main
  pull_request:
    branches:
      main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ./
    - run: pip install sphinx-lint>=0.9.0
    - run: sphinx-lint .github/file.rst >/dev/null
      continue-on-error: true
